name: Feature Request
description: Suggest a new rule, pattern, or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement!
        
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: "When using AI for X, I often encounter Y problem..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you solve this?
      placeholder: "Add a rule that..."
    validations:
      required: true
      
  - type: textarea
    id: example
    attributes:
      label: Real-World Example
      description: Share a concrete example where this helped
      placeholder: "In my project, I tried X and it resulted in Y..."
    validations:
      required: false
      
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Core Rules
        - Workflow
        - Quality
        - Stack Guide
        - Operations
        - Platform-Specific
        - Other
    validations:
      required: true
